### ISSUE TITLE
"User not found"

### ISSUE THREAD

**Issue by DaniSpringer** [freopen/chess-erdos#7]
But user exists. It should instead give the error of "user found but no num yet".
Username: SpringerDanielTwitch

**Comment by DaniSpringer** [comment]
@eskopp not sure why it wasn't working before... thanks!

Perhaps you might want to add a link to your project to your README

Thank you

Dani

**Comment by eskopp** [comment]
Hello @DaniSpringer,
I would just like to point out that neither the git nor the repo nor the finished product belongs to me. The whole thing belongs to the GitHub user @freopen. I legendarily saw your issue and entered your name on the website. I then took a screenshot for you. But I can imagine where the core problem lies. I tested the tool with 2 relatively new <50 games. It could not find a way and therefore displayed "User not found". I think the error message is just badly chosen.
With kind regards
@eskopp

**Comment by freopen** [comment]
Sorry, I didn't get the notification for some reason. This project reads dumps of lichess games from database.lichess.org. A new dump appears every month, so I can't access the games of the current month. If user played his first game during that month - I can't see him at all, that's why "User not found". The message could be clearer though.

**Comment by splakish** [comment]
@freopen I'm happy to contribute to improve error messages to handle different cases. What files should I look at?

Thanks
